import "@/styles/_base";
import type { Metadata } from "next";
import Navigation from "@/components/modules/Navigation";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TravelTale",
  description: "Generated by create turbo",
};

const links = [
  {
    label: "Home",
    url: "/",
    icon: "FiGrid",
  },
  {
    label: "Post",
    url: "/post",
    icon: "FiPlusCircle",
  },
  {
    label: "Profile",
    url: "/profile",
    icon: "FiUser",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navigation links={links} />
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
